### ISSUE TITLE
DistributedLockTimeoutException with Hangfire.Storage.SQLite

### ISSUE THREAD

**Issue by 0xced** [raisedapp/Hangfire.Storage.SQLite#32]
I'm sorry I don't know how to reliably reproduce this exception. All I can tell you is that `MyJobClass.MyJobMethod` has this attribute: `[DisableConcurrentExecution(timeoutInSeconds: 10 * 60)]` and that I'm using a [TransactionScope](https://docs.microsoft.com/en-us/dotnet/api/system.transactions.transactionscope) to create two dependent jobs.
```
Hangfire.AutomaticRetryAttribute|Failed to process the job '123': an exception occurred. Retry attempt 1 of 10 will be performed in 00:00:39.
Hangfire.Storage.DistributedLockTimeoutException: Timeout expired. The timeout elapsed prior to obtaining a distributed lock on the 'Could not place a lock on the resource 'HangFire:MyJobClass.MyJobMethod': The lock request timed out.' resource.
   at void Hangfire.Storage.SQLite.SQLiteDistributedLock.Acquire(TimeSpan timeout)
   at new Hangfire.Storage.SQLite.SQLiteDistributedLock(string resource, TimeSpan timeout, HangfireDbContext database, SQLiteStorageOptions storageOptions)
   at IDisposable Hangfire.Storage.SQLite.HangfireSQLiteConnection.AcquireDistributedLock(string resource, TimeSpan timeout)
   at void Hangfire.DisableConcurrentExecutionAttribute.OnPerforming(PerformingContext filterContext)
   at bool Hangfire.Profiling.ProfilerExtensions.InvokeAction<TInstance>(InstanceAction<TInstance> tuple)
   at TResult Hangfire.Profiling.SlowLogProfiler.InvokeMeasured<TInstance, TResult>(TInstance instance, Func<TInstance, TResult> action, string message)
   at void Hangfire.Profiling.ProfilerExtensions.InvokeMeasured<TInstance>(IProfiler profiler, TInstance instance, Action<TInstance> action, string message)
   at PerformedContext Hangfire.Server.BackgroundJobPerformer.InvokePerformFilter(IServerFilter filter, PerformingContext preContext, Func<PerformedContext> continuation)
```

Anyway I switched to [HangFire.SqlServer](https://www.nuget.org/packages/HangFire.SqlServer/) and this problem did not occur anymore.

**Comment by rafibenavi** [comment]
Happens to us too. once every couple of days this occurs in production ... awful

**Comment by marce1994** [comment]
Same here :(

**Comment by gabrielsimas** [comment]
Solution:
In my case... i'm increase time to DistributedLock to 3 minutes via SQLiteStorageOptions

`.UseSQLiteStorage(sqlitePath, new SQLiteStorageOptions()
  {
      DistributedLockLifetime = TimeSpan.FromMinutes(3)
  })`

**Comment by felixclase** [comment]
I will try to reproduce this problem.

**Comment by todorovicg** [comment]
Same issue here. Using latest 0.2.5 version.

Timeout expired. The timeout elapsed prior to obtaining a distributed lock on the 'Could not place a lock on the resource 'HangFire:extension:job-mutex:lock:SyncJob': The lock request timed out.' resource.
   
   `at Hangfire.Storage.SQLite.SQLiteDistributedLock.Acquire(TimeSpan timeout)
   at Hangfire.Storage.SQLite.SQLiteDistributedLock..ctor(String resource, TimeSpan timeout, HangfireDbContext database, SQLiteStorageOptions storageOptions)
   at Hangfire.Storage.SQLite.HangfireSQLiteConnection.AcquireDistributedLock(String resource, TimeSpan timeout)`

**Comment by felixclase** [comment]
> Same issue here. Using latest 0.2.5 version.
> 
> Timeout expired. The timeout elapsed prior to obtaining a distributed lock on the 'Could not place a lock on the resource 'HangFire:extension:job-mutex🔒SyncJob': The lock request timed out.' resource.
> 
> `at Hangfire.Storage.SQLite.SQLiteDistributedLock.Acquire(TimeSpan timeout) at Hangfire.Storage.SQLite.SQLiteDistributedLock..ctor(String resource, TimeSpan timeout, HangfireDbContext database, SQLiteStorageOptions storageOptions) at Hangfire.Storage.SQLite.HangfireSQLiteConnection.AcquireDistributedLock(String resource, TimeSpan timeout)`

Please try with 0.2.6 version

**Comment by felixclase** [comment]
> Same issue here. Using latest 0.2.5 version.
> 
> Timeout expired. The timeout elapsed prior to obtaining a distributed lock on the 'Could not place a lock on the resource 'HangFire:extension:job-mutex🔒SyncJob': The lock request timed out.' resource.
> 
> `at Hangfire.Storage.SQLite.SQLiteDistributedLock.Acquire(TimeSpan timeout) at Hangfire.Storage.SQLite.SQLiteDistributedLock..ctor(String resource, TimeSpan timeout, HangfireDbContext database, SQLiteStorageOptions storageOptions) at Hangfire.Storage.SQLite.HangfireSQLiteConnection.AcquireDistributedLock(String resource, TimeSpan timeout)`

Please try with 0.3.0 version

**Comment by felixclase** [comment]
> Happens to us too. once every couple of days this occurs in production ... awful

Please try with 0.3.0 version

**Comment by felixclase** [comment]
> Same here :(

Please try with 0.3.0 version

**Comment by ProsserCJ** [comment]
Hello, I am getting this error with version 0.3.0 when enqueueing a job:

```
An unhandled exception has occurred while executing the request.
Hangfire.BackgroundJobClientException: Background job creation failed. See inner exception for details.
 ---> Hangfire.Storage.DistributedLockTimeoutException: Timeout expired. The timeout elapsed prior to obtaining a distributed lock on the 'Could not place a lock on the resource 'HangFire:job:22:state-lock': The lock request timed out.' resource.
   at Hangfire.Storage.SQLite.SQLiteDistributedLock.Acquire(TimeSpan timeout)
   at Hangfire.Storage.SQLite.SQLiteDistributedLock..ctor(String resource, TimeSpan timeout, HangfireDbContext database, SQLiteStorageOptions storageOptions)
   at Hangfire.Storage.SQLite.HangfireSQLiteConnection.AcquireDistributedLock(String resource, TimeSpan timeout)
   at Hangfire.Storage.StorageConnectionExtensions.AcquireDistributedJobLock(IStorageConnection connection, String jobId, TimeSpan timeout)
   at Hangfire.ContinuationsSupportAttribute.AddContinuation(ElectStateContext context, AwaitingState awaitingState)
   at Hangfire.States.StateMachine.InvokeOnStateElection(Tuple`2 x)
   at Hangfire.Profiling.ProfilerExtensions.InvokeAction[TInstance](InstanceAction`1 tuple)
   at Hangfire.Profiling.ProfilerExtensions.InvokeMeasured[TInstance](IProfiler profiler, TInstance instance, Action`1 action, String message)
   at Hangfire.States.StateMachine.ApplyState(ApplyStateContext initialContext)
   at Hangfire.Client.CoreBackgroundJobFactory.<>c__DisplayClass14_0.<Create>b__3(Int32 attempt)
   at Hangfire.Client.CoreBackgroundJobFactory.<>c__DisplayClass15_0.<RetryOnException>b__0(Int32 attempt)
   at Hangfire.Client.CoreBackgroundJobFactory.RetryOnException[T](Int32& attemptsLeft, Func`2 action)
```

We are using [continuations](https://www.hangfire.io/overview.html#continuations) and queue the job and all of its continuations at once. 

It usually works, but the error above occurs occasionally.
