### ISSUE TITLE
Background job creation failed -  An item with the same key has already been added. Key: CurrentCulture

### ISSUE THREAD

**Issue by mstiago** [raisedapp/Hangfire.Storage.SQLite#56]
Hello,

I'm trying to create several jobs, but after some jobs created, my application thrown this error.

Can help me?

Thanks,
mstiago

    Hangfire.BackgroundJobClientException: Background job creation failed. See inner exception for details.
    ---> System.ArgumentException: An item with the same key has already been added. Key: CurrentCulture
     at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
     at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
     at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
     at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
     at Hangfire.Storage.SQLite.SQLiteMonitoringApi.<>c__DisplayClass25_0.<JobDetails>b__0(HangfireDbContext _)
     at Hangfire.Console.States.ConsoleApplyStateFilter.OnStateApplied(ApplyStateContext context, IWriteOnlyTransaction transaction)
     at Hangfire.States.StateMachine.InvokeOnStateApplied(Tuple`2 x)
     at Hangfire.Profiling.ProfilerExtensions.InvokeAction[TInstance](InstanceAction`1 tuple)
     at Hangfire.Profiling.ProfilerExtensions.InvokeMeasured[TInstance](IProfiler profiler, TInstance instance, Action`1 action, String message)
     at Hangfire.States.StateMachine.ApplyState(ApplyStateContext initialContext)
     at Hangfire.Client.CoreBackgroundJobFactory.<>c__DisplayClass14_0.<Create>b__3(Int32 attempt)
     at Hangfire.Client.CoreBackgroundJobFactory.<>c__DisplayClass15_0.<RetryOnException>b__0(Int32 attempt)
     at Hangfire.Client.CoreBackgroundJobFactory.RetryOnException[T](Int32& attemptsLeft, Func`2 action)
    --- End of stack trace from previous location ---
     at Hangfire.Client.CoreBackgroundJobFactory.RetryOnException[T](Int32& attemptsLeft, Func`2 action)
     at Hangfire.Client.CoreBackgroundJobFactory.RetryOnException(Int32& attemptsLeft, Action`1 action)
     at Hangfire.Client.CoreBackgroundJobFactory.Create(CreateContext context)
     at Hangfire.Client.BackgroundJobFactory.<>c__DisplayClass12_0.<CreateWithFilters>b__0()
     at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)
     at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)
     at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)
     at Hangfire.Client.BackgroundJobFactory.Create(CreateContext context)
     at Hangfire.BackgroundJobClient.Create(Job job, IState state)
     --- End of inner exception stack trace ---
     at Hangfire.BackgroundJobClient.Create(Job job, IState state)
     at Infrastructure.BackgroundJobs.HangfireService.Enqueue(Expression`1 methodCall) in C:\Users\6110183\source\repos\ThomsonReuters.HighQIntegration\Infrastructure\BackgroundJobs\HangfireService.cs:line 16
     at Infrastructure.Strategies.Implementations.TimesheetStrategy.RunAsync() in C:\Users\6110183\source\repos\ThomsonReuters.HighQIntegration\Infrastructure\Strategies\Implementations\TimesheetStrategy.cs:line 95

**Comment by schroedermarius** [comment]
Got the same problem. It seems to me, that the culture filter is applied to client and server filters and due to this it has  the same filter 2 times.

**Comment by felixclase** [comment]
Hello,

This bug has been fixed in version 0.3.3

![image](https://user-images.githubusercontent.com/1153361/233396330-2c5317a5-cf43-416f-b5af-f04769383d71.png)

Try again
