### ISSUE TITLE
.net 9 SQLite.SQLiteException: Could not open database file: Data Source=./ServerJob.db;Mode=ReadWriteCreate; (CannotOpen)

### ISSUE THREAD

**Issue by codelovercc** [raisedapp/Hangfire.Storage.SQLite#76]
The `ServerJob.db` exists in application root folder and has right permissions. I have another sqlite db for application named `buz.db` using EfCore, and it works well.
Hangfire.AspNetCore 1.8.17

StackTrace:
```
SQLite.SQLiteException: Could not open database file: Data Source=./ServerJob.db;Mode=ReadWriteCreate; (CannotOpen)
   at SQLite.SQLiteConnection..ctor(SQLiteConnectionString connectionString)
   at SQLite.SQLiteConnection..ctor(String databasePath, SQLiteOpenFlags openFlags, Boolean storeDateTimeAsTicks)
   at Hangfire.Storage.SQLite.SQLiteStorage.<>c__DisplayClass9_0.<.ctor>b__0()
   at Hangfire.Storage.SQLite.SQLiteDbConnectionFactory.Create()
   at Hangfire.Storage.SQLite.SQLiteStorage.CreateAndOpenConnection()
   at Hangfire.Storage.SQLite.SQLiteStorage..ctor(SQLiteDbConnectionFactory dbConnectionFactory, SQLiteStorageOptions storageOptions)
   at Hangfire.Storage.SQLite.SQLiteStorage..ctor(String databasePath, SQLiteStorageOptions storageOptions)
   at Hangfire.Storage.SQLite.SQLiteStorageExtensions.UseSQLiteStorage(IGlobalConfiguration configuration, String nameOrConnectionString, SQLiteStorageOptions options)
```

**Comment by codelovercc** [comment]
I've tried use `Data Source= ServerJob.db;Mode=Memory;` , and it works well.

**Comment by codelovercc** [comment]
Turns out, It take a file path for sqlite database instead of a connection string :)

I use this method 
```
 public static IGlobalConfiguration<SQLiteStorage> UseSQLiteStorage(
      [NotNull] this IGlobalConfiguration configuration,
      [NotNull] string nameOrConnectionString,
      SQLiteStorageOptions options = null)
```
